server:
  port: 8888

spring:
  application:
    name: eureka-server
  profiles:
    active: dev


#eureka
eureka:
  instance:
    appname: eureka-server
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

